### ISSUE TITLE
Empty images after running imagemin repeatedly

### ISSUE THREAD

**Issue by snowman-repos** [gruntjs/grunt-contrib-imagemin#140]
- Freshly installed copy of Grunt 0.4.1 and grunt-contrib-imagemin 0.5.0
- No other tasks in the Gruntfile, just imagemin
- 3 fresh JPGs in the `/images` folder (1 image is 427kb)
- Running `grunt:imagemin` or `grunt` the first time results in over-optimised (blurry) images in the `images/optimised` folder. The 427kb jpeg reduced to 66kb, although the CLI reports "(saved 426.80 kB)".
- Running subsequent times results in **empty** (0kb) images. The command line continues to report "(saved 426.80 kB)".

```
imagemin: {
  dynamic: {
    files: [{
      expand: true,
      cwd: 'images/',
      src: ['*.{png,jpg,gif}'],
      dest: 'images/optimised/'
    }]
  }
}
```

**Comment by dudewad** [comment]
Mine dies on png files. The weird thing is that I've been using it for days, without modifying my grunt setup at all it just stopped working. I think this is somehow related to files because I did modify a significant number of files in my image directory.
I feel like it should be testing whether or not it is WRITING to the file it should be READING. That seems obvious. Could be a node issue? Bummer, because by now I could have optimized my files by hand anyways....
