### ISSUE TITLE
File names too long

### ISSUE THREAD

**Issue by aholla** [gruntjs/grunt-contrib-imagemin#260]
Can anything be done about the file names being ttoo long if you want to delete the directory in windows?

**Comment by DavidGilbertsonSMS** [comment]
OK I know this is a stupid Windows limitation, but I have to use Windows and Visual Studio for the project I'm on.

Since npm will never change the way dependencies are handled, and Windows will never fix the 260 character limit, I should simply conclude this module doesn't fully support use on Windows (it will also fail in a vagrant environment)?

I know this is a bit of a rant, but I'd love to see and end to the "well, you shouldn't be using windows, so too bad" mentality that sucks for devs that have no choice (and isaacs agrees: https://github.com/joyent/node/issues/6960#issuecomment-46704998).

So after all that I'm asking, is there no way this module could reduce its dependency tree so that it can be used with Windows?

C:\w\my-app\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle\node_modules\bin-build\node_modules\download\node_modules\decompress\node_modules\adm-zip\... and so on.

**Comment by ultrawebsites** [comment]
You could try installing some of the deeply nested npm dependency packages as direct dependencies of your project, which would prevent imagemin from needing to install/nest them at all, and help you get around this issue. There are also some other 'dedupe' or 'flatten' modules to help address this issue (just Google that). Bit of a pain but should work. As far as the original question regarding deleting the directories, just drag the ones you can't delete higher up in your file system, and then you can delete.
